{% if values.use_eks %}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${{values.component_id}}
  labels:
    app.kubernetes.io/name: ${{values.component_id}}
    backstage.io/kubernetes-id: ${{values.component_id}}
imagePullSecrets:
- name: artifactory
{% endif %}
